#!/usr/bin/env bash
# setup.sh — Linux/macOS setup for the Java→Python migration tool
set -euo pipefail

VENV_DIR=".venv"
ENV_FILE=".env"

# ── Colours ──────────────────────────────────────────────────────────────────
RED='\033[0;31m'; GREEN='\033[0;32m'; YELLOW='\033[1;33m'
CYAN='\033[0;36m'; BOLD='\033[1m'; RESET='\033[0m'

info()    { echo -e "${CYAN}[INFO]${RESET}  $*"; }
success() { echo -e "${GREEN}[OK]${RESET}    $*"; }
warn()    { echo -e "${YELLOW}[WARN]${RESET}  $*"; }
error()   { echo -e "${RED}[ERROR]${RESET} $*"; exit 1; }

# ── Python check ─────────────────────────────────────────────────────────────
info "Checking Python..."
PYTHON=$(command -v python3 || command -v python || true)
[ -z "$PYTHON" ] && error "Python 3.10+ not found. Install it and re-run."

PY_VER=$($PYTHON -c "import sys; print(f'{sys.version_info.major}.{sys.version_info.minor}')")
PY_MAJOR=$(echo "$PY_VER" | cut -d. -f1)
PY_MINOR=$(echo "$PY_VER" | cut -d. -f2)
(( PY_MAJOR < 3 || (PY_MAJOR == 3 && PY_MINOR < 10) )) && \
    error "Python 3.10+ required, found $PY_VER"
success "Python $PY_VER"

# ── Virtual environment ───────────────────────────────────────────────────────
if [ ! -d "$VENV_DIR" ]; then
    info "Creating virtual environment..."
    $PYTHON -m venv "$VENV_DIR"
    success "Created $VENV_DIR"
else
    info "Virtual environment already exists — skipping creation."
fi

# shellcheck source=/dev/null
source "$VENV_DIR/bin/activate"
info "Activated $VENV_DIR"

# ── Dependencies ─────────────────────────────────────────────────────────────
info "Installing dependencies..."
pip install --quiet --upgrade pip
pip install --quiet -r requirements.txt
success "Dependencies installed."

# ── Provider selection ───────────────────────────────────────────────────────
echo ""
echo -e "${BOLD}Select LLM provider:${RESET}"
echo "  1) Anthropic (claude-sonnet / claude-opus)"
echo "  2) GitHub Copilot (gpt-4o via github/)"
echo "  3) OpenAI (gpt-4o)"
echo ""
read -rp "Enter choice [1-3]: " CHOICE

case "$CHOICE" in
  1)
    PROVIDER="anthropic"
    read -rsp "Anthropic API key (sk-ant-...): " API_KEY; echo
    KEY_VAR="ANTHROPIC_API_KEY"
    ;;
  2)
    PROVIDER="copilot"
    read -rsp "GitHub Copilot token (ghp_... or ghu_...): " API_KEY; echo
    KEY_VAR="GITHUB_COPILOT_TOKEN"
    ;;
  3)
    PROVIDER="openai"
    read -rsp "OpenAI API key (sk-...): " API_KEY; echo
    KEY_VAR="OPENAI_API_KEY"
    ;;
  *)
    error "Invalid choice."
    ;;
esac

[ -z "$API_KEY" ] && error "API key cannot be empty."

# ── Write .env ────────────────────────────────────────────────────────────────
info "Writing $ENV_FILE..."
cat > "$ENV_FILE" <<EOF
# Auto-generated by setup.sh — edit as needed

LLM_PROVIDER=${PROVIDER}
${KEY_VAR}=${API_KEY}

# Optional: override default models
# AGENT_MODEL=
# HUB_MODEL=

# Optional: Qdrant vector store (leave blank to skip)
# QDRANT_URL=http://localhost:6333
# QDRANT_API_KEY=

# Optional: GitHub integration
# GITHUB_TOKEN=
# GITHUB_REPO=owner/repo
EOF

success ".env written for provider: ${PROVIDER}"

# ── Done ─────────────────────────────────────────────────────────────────────
echo ""
echo -e "${GREEN}${BOLD}Setup complete!${RESET}"
echo ""
echo -e "  To activate the environment:  ${CYAN}source ${VENV_DIR}/bin/activate${RESET}"
echo -e "  To switch provider later:     edit ${CYAN}${ENV_FILE}${RESET}"
echo -e "  To run the migration:         ${CYAN}python main.py migrate sample_java/ --out ./output${RESET}"
echo ""
