#!/usr/bin/env bash
# setup.sh -- Linux/macOS setup for the Java->Python migration tool
set -euo pipefail

CONDA_ENV="vb_migration"
ENV_FILE=".env"

RED='\033[0;31m'; GREEN='\033[0;32m'; YELLOW='\033[1;33m'
CYAN='\033[0;36m'; BOLD='\033[1m'; RESET='\033[0m'

info()    { echo -e "${CYAN}[INFO]${RESET}  $*"; }
success() { echo -e "${GREEN}[OK]${RESET}    $*"; }
warn()    { echo -e "${YELLOW}[WARN]${RESET}  $*"; }
error()   { echo -e "${RED}[ERROR]${RESET} $*"; exit 1; }

# -- Environment setup --------------------------------------------------------
USE_CONDA=false

if command -v conda &>/dev/null; then
    info "Conda detected -- using conda environment '$CONDA_ENV'"
    USE_CONDA=true

    # Enable 'conda activate' inside this script
    CONDA_BASE=$(conda info --base)
    # shellcheck source=/dev/null
    source "$CONDA_BASE/etc/profile.d/conda.sh"

    if conda env list | grep -qE "^${CONDA_ENV}[[:space:]]"; then
        info "Conda env '$CONDA_ENV' already exists -- skipping creation."
    else
        info "Creating conda env '$CONDA_ENV' with Python 3.10..."
        conda create -y -n "$CONDA_ENV" python=3.10 2>&1 | tail -3
        success "Created conda env '$CONDA_ENV'"
    fi

    conda activate "$CONDA_ENV"
    success "Activated conda env '$CONDA_ENV'"

else
    warn "Conda not found -- falling back to Python venv"
    VENV_DIR=".venv"

    PYTHON=$(command -v python3 || command -v python || true)
    [ -z "$PYTHON" ] && error "Python 3.10+ not found. Install Miniconda (https://docs.conda.io) or Python and re-run."

    PY_VER=$($PYTHON -c "import sys; print(f'{sys.version_info.major}.{sys.version_info.minor}')")
    PY_MAJOR=$(echo "$PY_VER" | cut -d. -f1)
    PY_MINOR=$(echo "$PY_VER" | cut -d. -f2)
    (( PY_MAJOR < 3 || (PY_MAJOR == 3 && PY_MINOR < 10) )) && \
        error "Python 3.10+ required, found $PY_VER"
    success "Python $PY_VER"

    if [ ! -d "$VENV_DIR" ]; then
        info "Creating virtual environment..."
        $PYTHON -m venv "$VENV_DIR"
        success "Created $VENV_DIR"
    else
        info "Virtual environment already exists -- skipping creation."
    fi

    # shellcheck source=/dev/null
    source "$VENV_DIR/bin/activate"
    info "Activated $VENV_DIR"
fi

# -- Dependencies -------------------------------------------------------------
info "Installing dependencies..."
python -m pip install --quiet --upgrade pip
pip install --quiet -r requirements.txt
success "Dependencies installed."

# -- Provider selection -------------------------------------------------------
echo ""
echo -e "${BOLD}Select LLM provider:${RESET}"
echo "  1) Anthropic (claude-sonnet / claude-opus)"
echo "  2) GitHub Copilot (gpt-4o via github/)"
echo "  3) OpenAI (gpt-4o)"
echo ""
read -rp "Enter choice [1-3]: " CHOICE

case "$CHOICE" in
  1) PROVIDER="anthropic"; KEY_VAR="ANTHROPIC_API_KEY" ;;
  2) PROVIDER="copilot";   KEY_VAR="GITHUB_COPILOT_TOKEN" ;;
  3) PROVIDER="openai";    KEY_VAR="OPENAI_API_KEY" ;;
  *) error "Invalid choice." ;;
esac

# -- Endpoint selection -------------------------------------------------------
echo ""
echo -e "${BOLD}Endpoint type:${RESET}"
echo "  1) Personal  — use the provider's standard API endpoint"
echo "  2) Company   — use a company proxy / custom endpoint URL"
echo ""
read -rp "Enter choice [1-2]: " ENDPOINT_CHOICE

LLM_API_BASE=""
API_KEY=""
case "$ENDPOINT_CHOICE" in
  1)
    read -rsp "API key: " API_KEY; echo
    ;;
  2)
    read -rp  "Company endpoint URL (e.g. https://proxy.company.com/v1): " LLM_API_BASE
    [ -z "$LLM_API_BASE" ] && error "Endpoint URL cannot be empty."
    read -rsp "API key: " API_KEY; echo
    ;;
  *) error "Invalid choice." ;;
esac

[ -z "$API_KEY" ] && error "API key cannot be empty."

# -- Write .env ---------------------------------------------------------------
info "Writing $ENV_FILE..."

API_BASE_LINE=""
[ -n "$LLM_API_BASE" ] && API_BASE_LINE="LLM_API_BASE=${LLM_API_BASE}"

cat > "$ENV_FILE" <<EOF
# Auto-generated by setup.sh -- edit as needed

LLM_PROVIDER=${PROVIDER}
${KEY_VAR}=${API_KEY}
${API_BASE_LINE}

# Optional: override default models
# AGENT_MODEL=
# HUB_MODEL=

# Optional: Qdrant vector store (leave blank to skip)
# QDRANT_URL=http://localhost:6333
# QDRANT_API_KEY=

# Optional: GitHub integration
# GITHUB_TOKEN=
# GITHUB_REPO=owner/repo
EOF

success ".env written for provider: ${PROVIDER}"

# -- Done ---------------------------------------------------------------------
echo ""
echo -e "${GREEN}${BOLD}Setup complete!${RESET}"
echo ""
if [ "$USE_CONDA" = true ]; then
    echo -e "  Activate the environment:  ${CYAN}conda activate ${CONDA_ENV}${RESET}"
else
    echo -e "  Activate the environment:  ${CYAN}source ${VENV_DIR}/bin/activate${RESET}"
fi
echo -e "  Switch provider later:     edit ${CYAN}${ENV_FILE}${RESET}"
echo -e "  Run the migration:         ${CYAN}python main.py migrate sample_java/ --out ./output${RESET}"
echo ""
