# setup.ps1 — Windows setup for the Java→Python migration tool
# Run with: powershell -ExecutionPolicy Bypass -File setup.ps1

$ErrorActionPreference = "Stop"
$VENV_DIR = ".venv"
$ENV_FILE = ".env"

function Info    { param($msg) Write-Host "[INFO]  $msg"  -ForegroundColor Cyan   }
function Success { param($msg) Write-Host "[OK]    $msg"  -ForegroundColor Green  }
function Warn    { param($msg) Write-Host "[WARN]  $msg"  -ForegroundColor Yellow }
function Fail    { param($msg) Write-Host "[ERROR] $msg"  -ForegroundColor Red; exit 1 }

# ── Python check ──────────────────────────────────────────────────────────────
Info "Checking Python..."
$PYTHON = $null
foreach ($cmd in @("python", "python3", "py")) {
    try {
        $ver = & $cmd --version 2>&1
        if ($ver -match "Python (\d+)\.(\d+)") {
            $major = [int]$Matches[1]; $minor = [int]$Matches[2]
            if ($major -gt 3 -or ($major -eq 3 -and $minor -ge 10)) {
                $PYTHON = $cmd; break
            }
        }
    } catch {}
}
if (-not $PYTHON) { Fail "Python 3.10+ not found. Install it from https://python.org and re-run." }
$pyVer = (& $PYTHON --version 2>&1) -replace "Python ", ""
Success "Python $pyVer"

# ── Virtual environment ───────────────────────────────────────────────────────
if (-not (Test-Path $VENV_DIR)) {
    Info "Creating virtual environment..."
    & $PYTHON -m venv $VENV_DIR
    Success "Created $VENV_DIR"
} else {
    Info "Virtual environment already exists — skipping creation."
}

$activateScript = Join-Path $VENV_DIR "Scripts\Activate.ps1"
if (-not (Test-Path $activateScript)) { Fail "Activation script not found: $activateScript" }
. $activateScript
Info "Activated $VENV_DIR"

# ── Dependencies ──────────────────────────────────────────────────────────────
Info "Installing dependencies..."
& pip install --quiet --upgrade pip
& pip install --quiet -r requirements.txt
Success "Dependencies installed."

# ── Provider selection ────────────────────────────────────────────────────────
Write-Host ""
Write-Host "Select LLM provider:" -ForegroundColor White
Write-Host "  1) Anthropic (claude-sonnet / claude-opus)"
Write-Host "  2) GitHub Copilot (gpt-4o via github/)"
Write-Host "  3) OpenAI (gpt-4o)"
Write-Host ""
$choice = Read-Host "Enter choice [1-3]"

switch ($choice) {
    "1" {
        $provider = "anthropic"
        $apiKey   = Read-Host "Anthropic API key (sk-ant-...)" -AsSecureString
        $keyVar   = "ANTHROPIC_API_KEY"
    }
    "2" {
        $provider = "copilot"
        $apiKey   = Read-Host "GitHub Copilot token (ghp_... or ghu_...)" -AsSecureString
        $keyVar   = "GITHUB_COPILOT_TOKEN"
    }
    "3" {
        $provider = "openai"
        $apiKey   = Read-Host "OpenAI API key (sk-...)" -AsSecureString
        $keyVar   = "OPENAI_API_KEY"
    }
    default { Fail "Invalid choice." }
}

# Convert SecureString → plain text
$plainKey = [System.Runtime.InteropServices.Marshal]::PtrToStringAuto(
    [System.Runtime.InteropServices.Marshal]::SecureStringToBSTR($apiKey)
)
if ([string]::IsNullOrWhiteSpace($plainKey)) { Fail "API key cannot be empty." }

# ── Write .env ────────────────────────────────────────────────────────────────
Info "Writing $ENV_FILE..."
@"
# Auto-generated by setup.ps1 — edit as needed

LLM_PROVIDER=$provider
$keyVar=$plainKey

# Optional: override default models
# AGENT_MODEL=
# HUB_MODEL=

# Optional: Qdrant vector store (leave blank to skip)
# QDRANT_URL=http://localhost:6333
# QDRANT_API_KEY=

# Optional: GitHub integration
# GITHUB_TOKEN=
# GITHUB_REPO=owner/repo
"@ | Set-Content -Encoding UTF8 $ENV_FILE

Success ".env written for provider: $provider"

# ── Done ──────────────────────────────────────────────────────────────────────
Write-Host ""
Write-Host "Setup complete!" -ForegroundColor Green
Write-Host ""
Write-Host "  Activate the environment:  " -NoNewline
Write-Host "$VENV_DIR\Scripts\Activate.ps1" -ForegroundColor Cyan
Write-Host "  Switch provider later:     edit " -NoNewline
Write-Host $ENV_FILE -ForegroundColor Cyan
Write-Host "  Run the migration:         " -NoNewline
Write-Host "python main.py migrate sample_java/ --out .\output" -ForegroundColor Cyan
Write-Host ""
