"""
GitHub MCP Server

Creates a feature branch and pull request for each successfully migrated module.
Requires GITHUB_TOKEN and GITHUB_REPO in .env. Falls back gracefully if absent.
Start: python infrastructure/servers/github_server.py
"""
import asyncio
import json
import sys
from pathlib import Path

import mcp.server.stdio
import mcp.types as types
from mcp.server import NotificationOptions, Server
from mcp.server.models import InitializationOptions

sys.path.insert(0, str(Path(__file__).parent.parent.parent))
from config import Config  # noqa: E402

server = Server("vb2py-github")

_gh = None
_repo = None
_GithubException = None
_available = False


def _init_github() -> None:
    global _gh, _repo, _GithubException, _available
    if not Config.GITHUB_TOKEN or not Config.GITHUB_REPO:
        sys.stderr.write("GitHub credentials not configured — PR creation disabled.\n")
        return
    try:
        from github import Github, GithubException

        _gh = Github(Config.GITHUB_TOKEN)
        _repo = _gh.get_repo(Config.GITHUB_REPO)
        _GithubException = GithubException
        _available = True
        sys.stderr.write(f"GitHub connected → {Config.GITHUB_REPO}\n")
    except Exception as exc:
        sys.stderr.write(f"GitHub unavailable. ({exc})\n")


@server.list_tools()
async def list_tools() -> list[types.Tool]:
    return [
        types.Tool(
            name="create_pr",
            description=(
                "Commit a migrated Python file on a feature branch "
                "and open a GitHub pull request. Returns the PR URL or null."
            ),
            inputSchema={
                "type": "object",
                "properties": {
                    "module_name": {"type": "string"},
                    "python_file_path": {"type": "string"},
                    "python_code": {"type": "string"},
                    "test_results_summary": {"type": "string"},
                },
                "required": ["module_name", "python_file_path", "python_code", "test_results_summary"],
            },
        ),
    ]


@server.call_tool()
async def call_tool(name: str, arguments: dict | None) -> list[types.TextContent]:
    args = arguments or {}

    if name == "create_pr":
        if not _available or not _repo or not _GithubException:
            return [types.TextContent(type="text", text=json.dumps({"url": None}))]

        module_name = args["module_name"]
        python_file_path = Path(args["python_file_path"])
        python_code = args["python_code"]
        test_results_summary = args["test_results_summary"]
        branch = f"migration/{module_name.lower().replace(' ', '-')}"

        try:
            base = _repo.get_branch("main")
            try:
                _repo.create_git_ref(f"refs/heads/{branch}", base.commit.sha)
            except _GithubException:
                pass  # branch already exists

            rel_path = f"src/{python_file_path.name}"
            try:
                existing = _repo.get_contents(rel_path, ref=branch)
                _repo.update_file(
                    rel_path,
                    f"chore: update {module_name} migration",
                    python_code,
                    existing.sha,
                    branch=branch,
                )
            except _GithubException:
                _repo.create_file(
                    rel_path,
                    f"feat: migrate {module_name} Java → Python",
                    python_code,
                    branch=branch,
                )

            pr = _repo.create_pull(
                title=f"[Migration] {module_name}: Java → Python",
                body=_pr_body(module_name, test_results_summary),
                head=branch,
                base="main",
            )
            return [types.TextContent(type="text", text=json.dumps({"url": pr.html_url}))]

        except Exception as exc:
            sys.stderr.write(f"GitHub PR creation failed: {exc}\n")
            return [types.TextContent(type="text", text=json.dumps({"url": None, "error": str(exc)}))]

    raise ValueError(f"Unknown tool: {name}")


def _pr_body(module_name: str, test_summary: str) -> str:
    return f"""## Migration: {module_name}

Automated Java → Python migration via the Migration Orchestrator pipeline.

### Pipeline Steps Completed
- [x] Step 1 — Discovery, Documentation & Architecture
- [x] Step 2 — Test-Driven Development (Functional + Golden Master)
- [x] Step 3 — Conversion & Closed-Loop Execution

### Test Results
```
{test_summary}
```

---
*Generated by Java → Python Migration Orchestrator*
"""


async def main() -> None:
    _init_github()
    async with mcp.server.stdio.stdio_server() as (read_stream, write_stream):
        await server.run(
            read_stream,
            write_stream,
            InitializationOptions(
                server_name="vb2py-github",
                server_version="0.1.0",
                capabilities=server.get_capabilities(
                    notification_options=NotificationOptions(),
                    experimental_capabilities={},
                ),
            ),
        )


if __name__ == "__main__":
    asyncio.run(main())
